
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kszyokancjhnxykowaiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzenlva2FuY2pobnh5a293YWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODgzMTcsImV4cCI6MjA1ODU2NDMxN30.Jh0rHXXqx1qody_jmrq6rJnV3TU3z97EYE5HkbsaGO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase.auth.token',
  }
});

// Helper function to generate a UUID (v4)
export const generateUUID = () => {
  return crypto.randomUUID();
};
